# Generated by Django 6.0.2 on 2026-02-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
