# Generated by Django 5.2.7 on 2026-03-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
